---

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - "prealloc"
    - "misspell" # due to the package name (configue)
  enable-all: true

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-blank: true
    check-type-assertions: true
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: "github.com/krostar/configue"
  govet:
    use-installed-packages: true
  lll:
    tab-width: 4
  maligned:
    suggest-new: true
  misspell:
    locale: "US"
  unparam:
    check-exported: true

...
